### PR TITLE
Nothing

### PR DESCRIPTION
**Pull request by itsmechinmoy**

### CODE REVIEW

**Comment by Adolar0042** [comment]
@aayush2622 you gotta check PRs before you merge them :moyai: 
This (for whatever reason) refers to Dartotsu instead of Dantotsu

**Comment by itsmechinmoy** [comment]
mb 😢

**Comment by aayush2622** [comment]
@Adolar0042 My blind trust will be my downfall

**Comment by grayankit** [comment]
How does that even happen 😭

**Comment by itsmechinmoy** [comment]
> How does that even happen 😭

was adding them in both dantotsu and dartotsu

**Pull request merged**
