### PR TITLE
revert better regex

### PR DESCRIPTION
**Pull request by Yutatsu0**
fix episode number not being removed from the episode title in the latest pretest build

### CODE REVIEW

**Comment by rebelonion** [comment]
Sub/dub is necessary

**Comment by Yutatsu0** [comment]
> Sub/dub is necessary

why

**Comment by rebelonion** [comment]
Because if a title is ep 1 (sub) and remove just ep 1 the title becomes (sub) and looks weird

**Comment by Yutatsu0** [comment]
> Because if a title is ep 1 (sub) and remove just ep 1 the title becomes (sub) and looks weird

I think only allanime does that

**Comment by rebelonion** [comment]
And?
That doesn't mean it should be ignored

**Comment by Yutatsu0** [comment]
alright

**Pull request closed without merging**
