### PR TITLE
Include all Splits for discord

### PR DESCRIPTION
**Pull request by Sadwhy**

### CODE REVIEW

**Comment by Sadwhy** [comment]
Temporary fix

**Comment by AbandonedCart** [comment]
Did you mean to send 5 rapid fire messages?

**Comment by Sadwhy** [comment]
> Did you mean to send 5 rapid fire messages?

Ye

**Comment by Sadwhy** [comment]
> Alright. Just making sure, since sometimes that triggers spam protection.

If that was a problem I would just tell a mod to exclude that channel from protection. Besides do you not have a discord account?

**Comment by Sadwhy** [comment]
Screenshot_20240405_182835
You told me to do it @rebelonion

**Comment by AbandonedCart** [comment]
> Besides do you not have a discord account?

I didn't join this server. I never said I didn't have an account. It was only a question.

**Review by rebelonion — APPROVED** [review]

**Pull request merged**
