### PR TITLE
this, next, previous season centre align.

### PR DESCRIPTION
**Pull request by Shebyyy**

### CODE REVIEW

**Comment by Shebyyy** [comment]
@rebelonion 
please check and revert.

https://github.com/rebelonion/Dantotsu/assets/83452219/01ac3160-2fb7-4a4f-b6f5-34b5bf1459df

**Comment by aayush2622** [comment]
👍

**Comment by aayush2622** [comment]
But push to dev branch not main

**Comment by Shebyyy** [comment]
> But push to dev branch not main

oh sorry

**Pull request closed without merging**
