### PR TITLE
Supporting manual repo entry

### PR DESCRIPTION
**Pull request by AbandonedCart**

### CODE REVIEW

**Comment by AbandonedCart** [comment]
It was essentially already set up to work. It's just the pageantry of entry boxes and preferences and stuff.

**Comment by sneazy-ibo** [comment]
Nice I was about to suggest this, having all extensions directly accessible through dantotsu feels kinda unsafe regarding dmca

**Comment by AbandonedCart** [comment]
I think I went a level too high on that last one

**Comment by ARIF683** [comment]
Where you are doing this, can you fix some extension not able to search anime/manga, because of different language ig maybe.

**Comment by rebelonion** [comment]
be more specific

**Comment by ARIF683** [comment]
> be more specific

It my sleeping time, i would tell you some of the extension name in morning.
Sorry lol 😴

**Comment by AbandonedCart** [comment]
I guess this should support more than one. We all kinda know that doesn't actually matter

**Comment by AbandonedCart** [comment]
index.min.json is standard across these things, right? Nobody is throwing in a random ipostedextensionstoread.json?

**Comment by sneazy-ibo** [comment]
> While you are doing this, can you fix some extension not able to search anime/manga, because of different language ig maybe.

It happens on ComicK quite a lot

image

**Comment by rebelonion** [comment]
> index.min.json is standard across these things, right? Nobody is throwing in a random ipostedextensionstoread.json?

should be, yes

**Comment by AbandonedCart** [comment]
Alright. The less it needs to actually save, the better

**Comment by AbandonedCart** [comment]
So now it just needs the ability to delete a repo

**Comment by AbandonedCart** [comment]
Looks like the rebase even took care of the random newlines.

**Comment by AbandonedCart** [comment]
It's been done for practically a week. I marked it a draft because it's a big Band-Aid to tear off.

**Comment by AbandonedCart** [comment]
If you look at the lawsuit against yuzu, the fact that they didn't include the keys directly meant nothing because they provided instruction and resources to get them. That means removing the repo isn't enough to keep you safe from a shutdown. You can't go giving it out on Discord instead.

That aside, I need to make sure it doesn't overwrite the recent icon changes.

**Comment by rebelonion** [comment]
>  You can't go giving it out on Discord instead

We've had a rule in the discord banning extension recommendations for a few months now

**Comment by rebelonion** [comment]
yeah and my plan to make the transition easier for previous users is release one version that allows input, but has the one defaulted and stored. Then all versions after that the user would have to enter

**Comment by AbandonedCart** [comment]
Sounds like you're really banking on them being stupid.

**Comment by rebelonion** [comment]
Nah, I just care about my sanity dealing with the users

**Comment by AbandonedCart** [comment]
The mistake was not starting off with manual entry. Too late to change history, though. If you want to do something to ease the transition, that's on you.

**Pull request merged**
