### PR TITLE
fix: weights reflect other views

### PR DESCRIPTION
**Pull request by AbandonedCart**

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Not sure how it has no conflicts, considering it's essentially a direct conflict.

**Comment by AbandonedCart** [comment]
Anyway, setting the weight of the bottombar to 0 (the wrap_content equivalent of weights) will remove the warning

**Comment by rebelonion** [comment]
yolo

**Comment by AbandonedCart** [comment]
Still not 100% on why it loads random chunks of views, but I'm going to assume that probably caused it, too. Profile page was doing the same when I was originally testing, but that has the right weights and widths

**Comment by AbandonedCart** [comment]
... or not?

**Pull request closed without merging**
