### PR TITLE
remove rotate  button from exoplayer if pip is disabled

### PR DESCRIPTION
**Pull request by Yutatsu1**

### CODE REVIEW

**Comment by rebelonion** [comment]
you are aware that you are only hiding the rotate button if the pip button setting is enabled, correct?

**Comment by Yutatsu1** [comment]
> you are aware that you are only hiding the rotate button if the pip button setting is enabled, correct?

no if the pip button setting is disabled if pip button setting is enabled the rotate button will work as usual

**Comment by rebelonion** [comment]
yeah, I misspoke. I was more referring to how you are tying that setting to pip
would it not be better just to have it's own setting?

**Comment by Yutatsu1** [comment]
> yeah, I misspoke. I was more referring to how you are tying that setting to pip would it not be better just to have it's own setting?

I did that cause the pip mode causes the player go portrait and having rotate button when pip is enabled let's you go landscape again if you wanna make it's own setting then do it

**Comment by rebelonion** [comment]
ed19aac55358f4c89e3ff6f3b3ba0d7685d1a8e2

**Pull request closed without merging**
