### PR TITLE
fix: exo / subtitle improvements

### PR DESCRIPTION
**Pull request by AbandonedCart**
Extracted from the changes for torrents. Appears to fix whatever is going on with https://github.com/rebelonion/Dantotsu/issues/334

### CODE REVIEW

**Comment by AbandonedCart** [comment]
https://github.com/rebelonion/Dantotsu/blob/40bebca84b0bc4571b0c1aa4f0e88a7f1a6622b4/app/src/main/java/ani/dantotsu/media/anime/ExoplayerView.kt#L1614-L1634

You probably won't need this. That should all be done in onTracksChanged

**Review by rebelonion — APPROVED** [review]

**Comment by rebelonion** [comment]
I've always hated exoplayer
their documentation is terrible

**Comment by AbandonedCart** [comment]
It's fragmented because they moved to a new repo between 2 and 3, so half of it starts in 2 and only gets updated in 3. They expect that you came from 2, not started in 3.

**Comment by rebelonion** [comment]
my long term goal is to create a library from mpv and use that instead of exoplayer. May take a crack at it this summer

**Comment by AbandonedCart** [comment]
I think that's what kuukiyomi is using in theirs.

**Comment by rebelonion** [comment]
oh really? I didn't think anyone was using it on android other than [this](https://github.com/mpv-android/mpv-android). I have to take a look at kuukiyomi

**Pull request merged**
