### PR TITLE
fix: it was only an int for convenience

### PR DESCRIPTION
**Pull request by AbandonedCart**
Probably would have saved a lot of elaborate attempts to fix the issue by simply going the other way.

### CODE REVIEW

**Comment by rebelonion** [comment]
I'm not sure this will look any better with the examples I gave... but whatever ig 🤷‍♂️

**Comment by AbandonedCart** [comment]
You could always take a second and actually read the code.

**Comment by rebelonion** [comment]
dw I do

**Comment by AbandonedCart** [comment]
https://api.mangaupdates.com/#tag/releases/operation/searchReleasesPost

**Comment by AbandonedCart** [comment]
Which version of broken do you want? The one where it just randomly displays nothing or the one where a little formatting can make them all work?

**Comment by rebelonion** [comment]
one that doesn't crash firstly :)

**Comment by rebelonion** [comment]
although could just say something like "the last chapter aired on..." or something similar

**Comment by AbandonedCart** [comment]
Had anyone said what about when the chapter comes up as "Retribution", I would have realized that latestchapter is likely blank because they aren't using numbers, not the chapters were a string for convenience on their site.

**Pull request merged**
