### PR TITLE
fix: navbar covering info

### PR DESCRIPTION
**Pull request by sneazy-ibo**
added bottom layout margins in the following places to fix the navbar

### CODE REVIEW

**Comment by AbandonedCart** [comment]
That won't fix it. Clear the app from recents. It's probably because you've been reloading it trying to to do the search.

**Comment by AbandonedCart** [comment]
Try https://github.com/RepoDevil/Dantotsu/commit/c3131ea13557cae752bd6c9528d681f806bba1d9 and see if that solves the problem

**Comment by sneazy-ibo** [comment]
> because you can afford to make the padding too long and it won't break anything. If you start changing margins with all the code through the app meant to change and update the margins, it's not going to be consistent across devices.

I already had some worries regarding this so I gave some members in the discord server my apk to check if they had any issues but the margins were pretty fine with them. However this surely won't be the case so I am gonna adjust the code as you mentioned.

**Comment by sneazy-ibo** [comment]
> Try https://github.com/RepoDevil/Dantotsu/commit/c3131ea13557cae752bd6c9528d681f806bba1d9 and see if that solves the problem

I just tried it but the comments and fragments like statistics still get covered by the navbar

**Comment by AbandonedCart** [comment]
I'm not sure what you mean. Where are you when they get covered?

**Comment by AbandonedCart** [comment]
Might as well close this. Looks like they just went ahead and went with your original idea.

**Comment by aayush2622** [comment]
forgot ibo fixed it alr (why tf mfs pinging me in discord then 😢 :)

**Comment by AbandonedCart** [comment]
Because that's Discord.

**Comment by NerdyRay** [comment]
> forgot ibo fixed it alr (why tf mfs pinging me in discord then 😢 :)

😑😑😑😑

**Comment by AbandonedCart** [comment]
Well, now we know who that was about...

**Comment by NerdyRay** [comment]
> Well, now we know who that was about...

Yep that's me 😑

**Comment by AbandonedCart** [comment]
Welcome to GitHub! It's like Discord, but slower.

**Comment by NerdyRay** [comment]
> Welcome to GitHub! It's like Discord, but slower.

LoL

**Pull request closed without merging**
