### PR TITLE
fix: settings has over 80 views

### PR DESCRIPTION
**Pull request by AbandonedCart**
One really long layout is bad for performance, but this design also requires being aware of where an item is being placed.

Probably a bit too overwhelming, but just in case.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
I haven't tested all the buttons yet, so it may crash as is

**Comment by AbandonedCart** [comment]
Didn't hit EVERY button, but tried a couple in each section and everything appears to register.

**Comment by rebelonion** [comment]
I'm going to hold off on this and #255 until I push the next stable just in case they break something.
And just let me know when you think one of your PRs is ready to be looked at. No rush tho :)

**Comment by AbandonedCart** [comment]
Haven't found anything broken yet, but I know they are large changes.

**Comment by AbandonedCart** [comment]
I did a lot of cleanup to make this easier to follow, but it depends on some of the other changes in other PRs. It will have to wait.

**Comment by AbandonedCart** [comment]
https://github.com/RepoDevil/Dantotsu/commit/9a0ceb9a8c708e7b3becbb9559a711c8b1dcc76f is the end goal

**Pull request closed without merging**
