### PR TITLE
fix: lint warnings and cleanup

### PR DESCRIPTION
**Pull request by AbandonedCart**
This is part 1 of cleaning up all the lint issues. There were a lot of compat methods implemented, but not always used. A lot of methods with a context parameter that was unnecessary, A bunch of string resources as literals. Pretty much maintenance stuff that wasn't broken enough to need fixing. The catch being that it also increases the build time and slows down the app.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Android Studio performed any rename processes recursively.

**Comment by AbandonedCart** [comment]
Install isn't quite finished yet. It's a little larger because it's converting the intent to sessions

**Comment by AbandonedCart** [comment]
Bypassing user interaction doesn't appear to work. I'm also a bit confused why there's a separate flow for anime and manga. Any protest to merging them?

**Comment by rebelonion** [comment]
> Bypassing user interaction doesn't appear to work (prior to any changes). I'm also a bit confused why there's a separate flow for anime and manga. Any protest to merging them?

are you talking about the installer services for extensions?

**Comment by AbandonedCart** [comment]
Yes, it's two copies of the same code with the only difference being the UI that gets updated.

**Comment by rebelonion** [comment]
Yeah that code was basically copied from aniyomi with minimal changes. If u wanna merge them, sure

**Comment by AbandonedCart** [comment]
Ah, that explains it. That app is... rough.

**Comment by AbandonedCart** [comment]
I'm missing novels.

**Comment by rebelonion** [comment]
Novels were it's own thing I made that did not require an install

**Comment by AbandonedCart** [comment]
https://github.com/rebelonion/Dantotsu/blob/main/app/src/main/java/ani/dantotsu/parsers/novel/NovelExtensionInstaller.kt

^ I mean this

**Comment by AbandonedCart** [comment]
Looks like something broke.

**Comment by AbandonedCart** [comment]
The motel extension list isn't updating, but I also haven't checked if rerouting the installer needed other changes. I'll be going back to that next.

**Comment by AbandonedCart** [comment]
Screenshot_20240312_074109

**Comment by AbandonedCart** [comment]
Squashing the lint and extension changes together probably isn't a good idea.

**Comment by rebelonion** [comment]
hmmm I might end up just reverting novels to be installed as apks. The system I made is a bit janky... Eventually The plans is to create a way for all types of extensions to be downloaded internally without install

**Comment by AbandonedCart** [comment]
I left all the endpoints there and just didn't connect them to allow it to be merged later.

**Comment by AbandonedCart** [comment]
Missed an import

**Comment by AbandonedCart** [comment]
The last couple break the extension list. I still need to fix that.

**Comment by AbandonedCart** [comment]
A bug was introduced somewhere that causes the source selection to not update when an extension is installed or deleted until after a restart. I need to go back through everything.

**Comment by AbandonedCart** [comment]
I think anything else will just have to be done as it's discovered.

**Pull request closed without merging**
