### PR TITLE
Added Next Chapter Release Prediction

### PR DESCRIPTION
**Pull request by UmbrellaalAcademy**

### CODE REVIEW

**Comment by AbandonedCart** [comment]
I'd appreciate if you didn't copy and paste my work and submit it as your own. Thanks.

**Comment by brahmkshatriya** [comment]
> I'd appreciate if you didn't copy and paste my work and submit it as your own. Thanks.

Imagine if I said that

**Comment by AbandonedCart** [comment]
> Imagine if I said that

Do you not know how to use git, either? I'm just saying it was one commit and dude copied like 20 to make it.

**Comment by brahmkshatriya** [comment]
> > Imagine if I said that
> 
> Do you not know how to use git, either? I'm just saying it was one commit and dude copied like 20 to make it.

Uh Yea... can you teach me how to use git, I am new to this
I assume it was the same @UmbrellaalAcademy

**Comment by AbandonedCart** [comment]
> Uh Yea... can you teach me how to use git, I am new to this I assume it was the same @UmbrellaalAcademy

I'd be happy to help, but I have a feeling you're the only here not just playing developer.

**Comment by rebelonion** [comment]
did you even attempt to test this? this is in no way functioning code

**Pull request closed without merging**
