### PR TITLE
Remove (18+) extension if Anilist (18+) is off

### PR DESCRIPTION
**Pull request by aayush2622**
~requested by arif

### CODE REVIEW

**Comment by Sadwhy** [comment]
The problem with this is that general extensions like Mangadex and Comick will also get removed. There's just too many general purpose extension with the nsfw tag.

**Comment by Zaxx69** [comment]
True

**Comment by rebelonion** [comment]
> The problem with this is that general extensions like Mangadex and Comick will also get removed. There's just too many general purpose extension with the nsfw tag.

yeah that's a valid concern.
I'd either have to create a hardcoded whitelist or skip hiding all togehter.

**Comment by Sadwhy** [comment]
> > The problem with this is that general extensions like Mangadex and Comick will also get removed. There's just too many general purpose extension with the nsfw tag.
> 
> yeah that's a valid concern. I'd either have to create a hardcoded whitelist or skip hiding all togehter.

Hardcoding a whitelist is too much work when people are just gonna turn on 18+ mode anyway. It's not just worth it.

**Pull request closed without merging**
