### PR TITLE
fix: undo all of the margin hacks

### PR DESCRIPTION
**Pull request by AbandonedCart**
This fixes measuring the system navigation without needing to compensate in the AnimatedBottomBar and create a gap when the system navigation is not present (ie. landscape) and implements an updated library to support portrait stacking without multiple instances.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
I understand the profile page is still a bit trial and error, so leaving it as is may not have been the plan.

**Comment by AbandonedCart** [comment]
Is the media details bar over the camera in landscape for a reason or is it safe to move that?

**Comment by rebelonion** [comment]
are you talking about this?
image



>  I have a feeling getting them to stack is also why there are three individual instances instead of a single bar.

yeah the library doesn't support a vertical bar, so I made a custom controller

**Comment by AbandonedCart** [comment]
That part I got. I wasn't sure why it was over the front camera

**Comment by rebelonion** [comment]
If you were wondering why it was vertical to the side, it's because of the lack of space in landscape. I experimented with a horizontal one and people complained.

**Comment by AbandonedCart** [comment]
No, I was wondering why it was over the camera.

**Comment by rebelonion** [comment]
Ah.
No reason in particular.

**Comment by AbandonedCart** [comment]
I think the hardest part is trying to unravel the implementation to replace it with a proper library.

**Comment by rebelonion** [comment]
of the navbar? I quite like how it looks

**Comment by AbandonedCart** [comment]
No reason to change how it looks.

**Comment by AbandonedCart** [comment]
[Screen_recording_20240319_094811.webm](https://github.com/rebelonion/Dantotsu/assets/1173913/203f6822-4633-4633-a48b-693d68a0cec8)

**Comment by rebelonion** [comment]
Looks great 👍 
I personally am not a fan of the indicator bar in landscape mode. Looks a bit out of place.

**Comment by AbandonedCart** [comment]
> Looks great 👍 I personally am not a fan of the indicator bar in landscape mode. Looks a bit out of place.

See above

**Comment by AbandonedCart** [comment]
When you get the profile page sorted out, I can add it there, too.

**Comment by rebelonion** [comment]
I'd say the profile page is pretty much completed, so if you wanna add it there go ahead.

**Comment by rebelonion** [comment]
Would you say you're done with the media page?

**Comment by AbandonedCart** [comment]
I still need to make sure I grabbed all of the quirks from the old one.

**Comment by rebelonion** [comment]
Sounds good. I'm hoping to push a release in 12-ish hours and if this needs to wait, that's perfectly fine.

**Comment by AbandonedCart** [comment]
This is mostly backend performance. It's not going to fix any of the bugs with the UI.

**Comment by AbandonedCart** [comment]
I still think it's best to actually test it before throwing it straight into a release, but it's also not being published to Google Play or anything like that.

**Comment by AbandonedCart** [comment]
isNullOrBlank means null or (at most) only whitespace
isNullOrEmpty means null or zero length

**Review by rebelonion — APPROVED** [review]

**Comment by AbandonedCart** [comment]
Is the release process still going?

**Comment by rebelonion** [comment]
It's more or less done. I've just been busy the past 2 days. I should be able to go through the PRs today.

**Comment by AbandonedCart** [comment]
I can push the motherload on top of this one with all the conflicts already resolved if you like.

**Pull request closed without merging**
