### PR TITLE
feat: integrated profile editor

### PR DESCRIPTION
**Pull request by sneazy-ibo**
<details>
  <summary>Preview</summary>
image
</details>

### CODE REVIEW

**Comment by rebelonion** [comment]
what needs to be done with this?

**Comment by itsmechinmoy** [comment]
Updates?😔

**Comment by sneazy-ibo** [comment]
> what needs to be done with this?
> Updates?😔

The Query that needs to be used does not exists for free use, I spent like 5 days on this to end up here, it would be really nice if someone can find a alternative way for this so that my work does not go in vain 
image

**Comment by sneazy-ibo** [comment]
Toby found out that it needs cookies and other stuff in order to work, he has already implemented almost all of it except the schema.

```sh
curl 'https://anilist.co/graphql' --compressed -X POST -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:127.0) Gecko/20100101 Firefox/127.0' -H 'Accept: */*' -H 'Content-Type: application/json' -H 'schema: internal' -H 'x-csrf-token: <CSRF_TOKEN>' -H 'Origin: https://anilist.co' -H 'Connection: keep-alive' -H 'Cookie: laravel_session=<TOK>' -d @post_data
```
post data is just the variable that gets send with the mutation.

```
{"query":"mutation($avatar:String){SaveUserAvatar(avatar:$avatar){id avatar{large medium}}}","variables":{"avatar": "data:image/jpeg;base64,/9j/4AAQSkZJR this is imagedata encoded in base64 gABAgAAAQABAAD/"}}
```

**Comment by TehNut** [comment]
Hi, AniList owner here. Do not try to work around our limitations, I will block you. If it does not exist in the public API, it is not for you to use.

**Comment by sneazy-ibo** [comment]
my bad bro

**Comment by TobyBridle** [comment]
> Hi, AniList owner here. Do not try to work around our limitations, I will block you. If it does not exist in the public API, it is not for you to use.

Fair enough, I respect that. Won't see me working on it anymore, though I am interested in whether or not I would've got anywhere with it.
Thanks for your work :)

**Comment by Sadwhy** [comment]
We got the owner of anilist threatening Dantotsu before GTA VI

**Comment by grayankit** [comment]
We are threat to his existence

**Comment by Sadwhy** [comment]
> We are threat to his existence

Who's we?

**Pull request closed without merging**
