### PR TITLE
use episode titles from kitsu

### PR DESCRIPTION
**Pull request by Yutatsu0**
use episode titles from kitsu if kitsu doesn't have episode titles use episode titles from anime source

all the sources except aniwave, aniwatch, kaido, doesn't provide episode titles so using the episode titles from kitsu would be great

you can also try this artifact build and test it yourself
https://github.com/Yutatsu0/Dantotsu/actions/runs/7595023003/artifacts/1183041478

### CODE REVIEW

**Comment by aayush2622** [comment]
wow i did the same fix today still trying to find why th desc not working

**Comment by rebelonion** [comment]
So here's why I haven't done this myself: it's possible that the source returns the wrong anime, and the episodes are just numbered as usual. Now if we replace the titles with the expected anime titles, and that could lead to a lot of confusion when it does not match the anime the source returned.

**Comment by aayush2622** [comment]
:sadge:

**Comment by Yutatsu0** [comment]
> So here's why I haven't done this myself: it's possible that the source returns the wrong anime, and the episodes are just numbered as usual. Now if we replace the titles with the expected anime titles, and that could lead to a lot of confusion when it does not match the anime the source returned.

saikou used to have it though and there were some sources didn't provide episode titles and it used kitsu it was fine

**Comment by rebelonion** [comment]
Is this just thumbnails or descriptions as well? I'm not by my PC so I can't review it rn

**Comment by aayush2622** [comment]
sources send null so its already kitsu thumbnails and desc was changed so you gotta fix , this PR mainly have title. I tested it, it works

**Comment by Yutatsu0** [comment]
> Is this just thumbnails or descriptions as well? I'm not by my PC so I can't review it rn

every episode details first it will try to get it from kitsu if kitsu doesn't have it will fallback to anime source details

**Comment by rebelonion** [comment]
I misspoke. I meant title

**Comment by Yutatsu0** [comment]
> I misspoke. I meant title

yeah that was the main reason you can try the artifact build and see it yourself

**Review by rebelonion — APPROVED** [review]

**Pull request merged**
