### PR TITLE
Made it so you dont need to restart the app manually when changing the theme

### PR DESCRIPTION
**Pull request by JohnVictoryz**
i mean it does that if you want to see more about how and why are those needed check #279

### CODE REVIEW

**Comment by JohnVictoryz** [comment]
also i dont know why like it has so many commits i am sorry

**Comment by Sadwhy** [comment]
Nice now we somehow need a smooth transition

**Comment by JohnVictoryz** [comment]
> Nice now we somehow need a smooth transition

idk think that we can add a transition because it kills the app and relaunches it

**Comment by JohnVictoryz** [comment]
wait i will reopen
i just discarded the changes so i can remove like the conflicts

**Pull request closed without merging**
