### PR TITLE
Last chapter release since (updated)

### PR DESCRIPTION
**Pull request by minsoramune**
Updated version of <https://github.com/rebelonion/Dantotsu/blob/dev/app/src/main/java/ani/dantotsu/connections/bakaupdates/MangaUpdates.kt>

Feel free to make changes

### CODE REVIEW

**Review by minsoramune — COMMENTED** [review]
Some parenthesis fix

**Comment by aayush2622** [comment]
but why you are pushing to main branch?

**Comment by minsoramune** [comment]
> but why you are pushing to main branch?

Where should I have push it?

**Comment by aayush2622** [comment]
To dev branch

**Comment by minsoramune** [comment]
> To dev branch

F my mistake

**Pull request closed without merging**
