### PR TITLE
Added option to select the preferred language for subs (Resolves #239)

### LINKED ISSUE #239: Default subtitles language
A function that will save the subtitle language chosen on last episode (for softsub) like the default server function.

### PR DESCRIPTION
**Pull request by JohnVictoryz**
Added option to select the preferred language for subs basically just searches for the preferred sub language if no sub is selected manually 

also includes two functions that allows you to convert from the name of the language to the language code and another one that does the opposite

### CODE REVIEW

**Comment by JohnVictoryz** [comment]
man fuck git conflicts they don't make sense

**Comment by itsmechinmoy** [comment]
👀

**Comment by itsmechinmoy** [comment]
@JohnVictoryz will it still show the option for other language subs even if the server/extension doesn't support that language?

**Comment by JohnVictoryz** [comment]
> @JohnVictoryz will it still show the option for other language subs even if the server/extension doesn't support that language?

What do you mean this option just is for having preferred subs so if you want to change the subs to another language you can still change it to your preferred one I also was hoping to have a list of languages from like a library there is one but when you call the function it doesnt return a dictionary/array so I pretty much said f it and said that there arent a lot of subs for anime available anyway so I figured that I should just probably make a list with the most popular ones and just them

**Comment by JohnVictoryz** [comment]
i have this draft as i test it a bit and then i will undraft

**Comment by JohnVictoryz** [comment]
done

**Comment by grayankit** [comment]
you are done?
 if so provide some screenshots

**Comment by JohnVictoryz** [comment]
> you are done? if so can you provide some screenshots

i am done but what do you mean by screenshots there really is nothing fancy its just a menu that you select a language and the rest is code

**Comment by itsmechinmoy** [comment]
@grayankit tested?

**Comment by grayankit** [comment]
Working on another thing will do it sometime

**Review by grayankit — APPROVED** [review]
okay finally tested it ready to merge

**Pull request merged**
