### PR TITLE
Torrent

### PR DESCRIPTION
**Pull request by AbandonedCart**
Probably still bugs and the loading is absurd, but it works without leaving the app and integrates with the internal exoplayer

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Credit for the base code goes to https://github.com/LuftVerbot/kuukiyomi and the author has been attached to the commit

**Comment by rebelonion** [comment]
could the output stream be captured by ffmpeg for downloads?

**Comment by AbandonedCart** [comment]
Can your current videos?

**Comment by rebelonion** [comment]
I'm looking into transferring the downloads through ffmpeg so I don't have to deal with exoplayer's proprietary file types.

**Comment by AbandonedCart** [comment]
This is a torrent running on a virtual torrent server that's playing back the file as it downloads to cache.

**Comment by AbandonedCart** [comment]
I haven't looked deep enough to know if it's removing partial data as it plays, but it's more or less a download already.

**Comment by rebelonion** [comment]
now that I think about it, I'd be surprised if ffmpeg had trouble with it. I've already got it working with m3u8 and container streams.

**Comment by AbandonedCart** [comment]
There seem to be some lag issues associated with this, so I think I'll hold off a bit until I can sort that out.

**Pull request closed without merging**
