### PR TITLE
The motherload

### PR DESCRIPTION
**Pull request by AbandonedCart**
This supersedes #255, #259, #260 and #265 by combining them together and resolving the merge conflicts gracefully. Having tested all four extensively, I am now confident to lump them together.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Settings will look a little strange at first glance. Each expanding section is a layout. The order in the file matches the order on screen. Each binding for a section contains the code for the views it in. This makes the parent view `this` and the activity `this@SettingsActivity`. That way, you can call buttons and stuff directly without specifying the binding.

**Comment by AbandonedCart** [comment]
Looks like one of my local changes slipped into this. When you disable time stamps, the auto button is disabled. This matches the description that time stamps are required for auto to work.

**Comment by AbandonedCart** [comment]
The design looked much better before the cards, but I only addressed that the text overlaps the border. Honestly, it would have looked better with a single card around the whole thing.

**Comment by aayush2622** [comment]
alright. Done

**Comment by AbandonedCart** [comment]
<details><summary>The one shown above</summary>

```
                <com.google.android.material.card.MaterialCardView
                    android:id="@+id/profileButtonContainer"
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:layout_gravity="bottom"
                    android:layout_marginTop="210dp"
                    android:layout_marginBottom="6dp"
                    android:layout_marginHorizontal="8dp"
                    android:backgroundTint="?attr/colorSurfaceVariant"
                    android:baselineAligned="false"
                    tools:ignore="HardcodedText">
                    <LinearLayout
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:orientation="horizontal">

                        <LinearLayout
                            android:id="@+id/profileFollowerCountContainer"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_marginVertical="4dp"
                            android:layout_weight="1"
                            android:gravity="center"
                            android:layout_gravity="center"
                            android:backgroundTint="?attr/colorSurfaceVariant"
                            app:cardCornerRadius="16dp"
                            android:orientation="vertical">

                            <TextView
                                android:id="@+id/profileFollowerCount"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="center_horizontal"
                                android:fontFamily="@font/poppins_semi_bold"
                                android:textColor="?attr/colorPrimary"
                                tools:text="1" />

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="center_horizontal"
                                android:fontFamily="@font/poppins_semi_bold"
                                android:text="Follower" />
                        </LinearLayout>

                        <View
                            android:layout_width="2dp"
                            android:layout_height="match_parent"
                            android:layout_marginVertical="4dp"
                            android:background="?attr/colorAccent" />

                        <LinearLayout
                            android:id="@+id/profileFollowingCountContainer"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_marginVertical="4dp"
                            android:layout_weight="1"
                            android:gravity="center"
                            android:layout_gravity="center"
                            android:backgroundTint="?attr/colorSurfaceVariant"
                            app:cardCornerRadius="16dp"
                            android:orientation="vertical">

                            <TextView
                                android:id="@+id/profileFollowingCount"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="center_horizontal"
                                android:fontFamily="@font/poppins_semi_bold"
                                android:textColor="?attr/colorPrimary"
                                tools:text="2" />

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="center_horizontal"
                                android:fontFamily="@font/poppins_semi_bold"
                                android:text="Following" />
                        </LinearLayout>

                        <View
                            android:layout_width="2dp"
                            android:layout_height="match_parent"
                            android:layout_marginVertical="4dp"
                            android:background="?attr/colorAccent" />

                        <LinearLayout
                            android:id="@+id/profileAnimeCountContainer"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_marginVertical="4dp"
                            android:layout_weight="1"
                            android:gravity="center"
                            android:layout_gravity="center"
                            android:backgroundTint="?attr/colorSurfaceVariant"
                            app:cardCornerRadius="16dp"
                            android:orientation="vertical">

                            <TextView
                                android:id="@+id/profileAnimeCount"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="center_horizontal"
                                android:fontFamily="@font/poppins_semi_bold"
                                android:textColor="?attr/colorPrimary"
                                tools:text="3" />

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="center_horizontal"
                                android:fontFamily="@font/poppins_semi_bold"
                                android:text="Anime" />
                        </LinearLayout>

                        <View
                            android:layout_width="2dp"
                            android:layout_height="match_parent"
                            android:layout_marginVertical="4dp"
                            android:background="?attr/colorAccent" />

                        <LinearLayout
                            android:id="@+id/profileMangaCountContainer"
                            android:layout_width="0dp"
                            android:layout_height="wrap_content"
                            android:layout_marginVertical="4dp"
                            android:layout_weight="1"
                            android:gravity="center"
                            android:layout_gravity="center"
                            android:backgroundTint="?attr/colorSurfaceVariant"
                            app:cardCornerRadius="16dp"
                            android:orientation="vertical">

                            <TextView
                                android:id="@+id/profileMangaCount"
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="center_horizontal"
                                android:fontFamily="@font/poppins_semi_bold"
                                android:textColor="?attr/colorPrimary"
                                tools:text="4" />

                            <TextView
                                android:layout_width="wrap_content"
                                android:layout_height="wrap_content"
                                android:layout_gravity="center_horizontal"
                                android:fontFamily="@font/poppins_semi_bold"
                                android:text="Manga" />
                        </LinearLayout>
                    </LinearLayout>
                </com.google.android.material.card.MaterialCardView>
```
<\details>

**Comment by rebelonion** [comment]
slowly looking through the changes. will take a bit 😅

**Review by rebelonion — COMMENTED** [review]
just one question

**Comment by AbandonedCart** [comment]
```
API Changes

    Add isSystemRoute() to MediaRouteDescriptor and RouteInfo which returns true if the corresponding route is a system-managed route, which means that the system is the route provider and the app is in charge of feeding media samples to the system for their rendering (I949e4). Bluetooth headsets, wired headsets and built-in speakers are examples of system routes.
    Deprecate MediaRouter.removeRemoteControlClient. You should call setMediaSessionCompat(MediaSessionCompat) instead of addRemoteControlClient(Object) so that there is no need to call removeRemoteControlClient(Object). (I8fc5e).
    Make MediaRouteButton extend AppCompatImageView. (Ib455e).
    Add DEVICE_TYPE_SMARTPHONE, which indicates that a media route is a smartphone. (I39837).
    Improve device type mappings from MediaRouter2 to AndroidX MediaRouter to describe system routes (for example: Bluetooth, HDMI, wired). (Iccffa)

Bug Fixes

    Add missing icon resolutions for the route button that was possibly causing some isolated crashes. (cddba9, b/261878418).
    Fix bug causing isSystemRoute to return true for user routes added via android.media.MediaRouter#addUserRoute() (a27f6b).

New Features

    Bump the minSdk to 19. (e8c4463)
```

**Comment by AbandonedCart** [comment]
I'm not entirely fond of this being one giant PR, but there were overlapping issues and addressing them individually would create hours of extra work and a lot of redundancy to make each a self-contained PR.

If any one issue isn't going to be addressed, it can be dropped. Not intending to change something is completely different than trying to change the same thing multiple ways separately.

The issues being addressed are:

- The app navigation bars are hardcoded by the generic size of system navigation
- The AnimatedBottomBar does not support vertical orientation resulting in three entire RecyclerView instances to make one
- The settings page was one giant view with multiple large child views and the settings activity is all over the place
- Aniyomi was designed to be two sets of identical source instead of using variables, which doubles the file size
- The entire app is littered with hardcoded text, a lot of which is used repeatedly, preventing any translation

I'm not trying to be rude, but part of the reason this PR is so big is that it seems like the focus is only on adding more features and not fixing any of the broken ones you already have, or at least making it possible for others.

**Comment by rebelonion** [comment]
> that it seems like the focus is only on adding more features and not fixing any of the broken ones you already have

This isn't quite correct. I have been fixing many broken features while also adding new ones. As an example, the most recent feature I fixed the the subscription notification system, which has been a request since Dantotsu took over from Saikou.

My current workflow is about priority. Not to be rude, but nothing in this pr is that important to the functioning of the app. They're just small things that take time with little payoff in functionality or bugfixes.Things like hard coded text were ignored because I never planned on supporting other languages. The triple AnimatedBottomBar worked fine and the "messy" part was encapsulated away.

Now that's not to say I don't appreciate what's been changed here. There are better ways to do things (as you've shown in the PR), they just haven't are incredibly low priority for me to work on. 

> It's also perfectly fine if you don't want any of it. I'd just like to know that so I don't waste the time.

Of course I'm willing to merge fixes. I'll look over any final changes and ask you if I have questions, otherwise I'll merge.

**Comment by AbandonedCart** [comment]
I understand if my comment offended you a bit, but I think you are also missing the point. I was saying that things like the hardcoded strings create a roadblock for letting someone else do it. You don't want to translate, but responded to an issue about it that you would accept translations. Kinda slapping people in the face knowing they'll never appear, right?

**Comment by rebelonion** [comment]
I concede to that point.

**Comment by rebelonion** [comment]
But I'll still say my point about priority still stands. It is a lower priority fix for me, so I'm grateful you've worked on it.

**Comment by AbandonedCart** [comment]
This stuff sucks. I get that. I didn't do it because it was fun. I did it for what was possible after.

**Review by rebelonion — APPROVED** [review]

**Comment by AbandonedCart** [comment]
hmmm.. hide skip button shouldn't exist anymore. Oh, I see what happened.

**Comment by rebelonion** [comment]
https://github.com/rebelonion/Dantotsu/assets/87634197/d70c202c-bca2-4e1f-8b2f-9565ea768037

hmmm it seems something caused landscape to become very laggy

**Comment by AbandonedCart** [comment]
Did you clear the app from recents after the update? Something about how the new packagemanager updates things seems like it occasionally gets stale cache mixed in.

**Comment by rebelonion** [comment]
yeah this is being built in android studio. I've also had people report it in the alpha build (from github actions)

**Comment by AbandonedCart** [comment]
Weird. My landscape is smooth.

**Comment by AbandonedCart** [comment]
You don't happen to have a OnePlus or Xia(whatever the hell), do you?

**Comment by rebelonion** [comment]
I'm on Samasung

**Comment by rebelonion** [comment]
Also seems like fragments no longer account for the navbar

**Comment by AbandonedCart** [comment]
It could probably use a margin. Before, you ended up with a gap or it sunk below system navigation.

**Comment by rebelonion** [comment]
<details>
  <summary>Images</summary


</details>

The text on the left is also kinda broken

**Comment by rebelonion** [comment]
oh wait that's the other fragment. Why does it load halfway like that? 🤔

**Comment by AbandonedCart** [comment]
Yeah, that's one of the issues I was trying to fix by switching to a proper bar.

**Comment by rebelonion** [comment]
seems like it's the info fragment that causes the lag too.

**Comment by AbandonedCart** [comment]
Which is strange, since the only change there was to make the if something visible else gone lines into isvisible = something, which does the same function under the hood.

**Comment by rebelonion** [comment]
I'm running some profiling, and it seems to have something to do with Glide image loading. Looking into it.

**Comment by AbandonedCart** [comment]
I did notice you don't use kapt

**Comment by rebelonion** [comment]
weird. it seems to infinitely load the images in the adapters

**Comment by AbandonedCart** [comment]
I'm not at my computer now but I can look when I get back. They changed a lot randomly but I thought I saw the current target models

**Comment by AbandonedCart** [comment]
Screenshot_20240323_204447

That looks so cheesy with a margin

**Comment by AbandonedCart** [comment]
```
fun blurImage(imageView: ImageView, banner: String?) {
    if (banner != null) {
        val radius = PrefManager.getVal<Float>(PrefName.BlurRadius).toInt()
        val sampling = PrefManager.getVal<Float>(PrefName.BlurSampling).toInt()
        if (PrefManager.getVal(PrefName.BlurBanners)) {
            val context = imageView.context
            if (!(context as Activity).isDestroyed) {
                val url = PrefManager.getVal<String>(PrefName.ImageUrl).ifEmpty { banner }
                Glide.with(context as Context)
                    .load(GlideUrl(url))
                    .diskCacheStrategy(DiskCacheStrategy.ALL).override(400)
                    .apply(RequestOptions.bitmapTransform(BlurTransformation(radius, sampling)))
                    .into(imageView)
            }
        } else {
            imageView.loadImage(banner)
        }
    } else {
        imageView.setImageResource(R.drawable.linear_gradient_bg)
    }
}
```

That's one of your problems

**Comment by rebelonion** [comment]
I already tested with that disabled with no difference, but it's probably not necessary to have anyways.

**Comment by AbandonedCart** [comment]
The glitching was on a real device? I can't help thinking it's a network thing. I've been getting random anilist outages all day

**Comment by rebelonion** [comment]
I tested on real and emulated. ``onBindViewHolder`` in the adapters just get continuously called for some reason.

**Comment by AbandonedCart** [comment]
Sounds like a notifyItemChanged went rogue

**Comment by rebelonion** [comment]
https://github.com/rebelonion/Dantotsu/assets/87634197/c218034c-b692-4353-92a1-291f7d777568

what's weird is it works fine on some

**Comment by AbandonedCart** [comment]
Well, this is interesting....

**Comment by rebelonion** [comment]
So it seems to be tied to currently airing shows, possibly the countdown. But I think the issue is deeper as this doesn't happen in portrait. Another thing I noticed is all fragments load in landscape (they shouldn't), but they do not in portrait.

**Comment by AbandonedCart** [comment]
I think it's something with the api. The anime of the same name has a character list of only the first two characters.

**Comment by AbandonedCart** [comment]
Emulator locked up before I could rotate it.

**Comment by rebelonion** [comment]
Aha. setting ``android:layout_width="0dp"`` on the ``CoordinatorLayout`` causes the recylerviews to continuously update their width which causes a redraw when anything happens (like the countdown changing). I changed to ``match_parent`` and it seems to be fixed.

**Comment by AbandonedCart** [comment]
Yeah, I was just fixing it now. That was a merge conflict I thought my value was wrong for, but I also stumbled onto a search issue.

**Pull request merged**
