### PR TITLE
fix: data loading glitches

### PR DESCRIPTION
**Pull request by AbandonedCart**
I spun the wheel back and forth a few times and nothing broke, but I have never trusted onItemRange*

### CODE REVIEW

**Comment by AbandonedCart** [comment]
After I looked back at some other projects, I think only one of these is actually worth changing.

**Comment by AbandonedCart** [comment]
Did the layout fix the lag or is that still there?

**Comment by rebelonion** [comment]
yep

**Comment by AbandonedCart** [comment]
Next time Studio says "set a width of 0 for better performance" it better be right.

**Comment by AbandonedCart** [comment]
Kinda obvious nothing I watch is new, though.

**Comment by AbandonedCart** [comment]
The last one fixes that chunk of info that is still showing when you start on watch / read

**Comment by AbandonedCart** [comment]
Threw a couple small ones in with this because they aren't worth a whole PR.

**Review by rebelonion — APPROVED** [review]

**Pull request merged**
