### PR TITLE
feat: add some emotion to emojis

### PR DESCRIPTION
**Pull request by AbandonedCart**
312061765-de691651-895e-4b73-9904-6c60c6525a0e

### CODE REVIEW

**Comment by rebelonion** [comment]
honestly I quite like the emoticons

**Comment by AbandonedCart** [comment]
I'm still a bit confused by the donation dialog. It appears over a donation button.

**Comment by rebelonion** [comment]
iirc it has a random chance to pop up when opening the settings for more visibility.

**Comment by AbandonedCart** [comment]
It's on a timer. I was saying I don't entirely get putting it on top of the existing button and not like on the home page.

**Comment by rebelonion** [comment]
you're more likely to notice a popup, but being on the home page would be annoying. So it's a balance

**Comment by AbandonedCart** [comment]
The button on the homepage. The popup in settings.

**Pull request closed without merging**
