### PR TITLE
feat(discord): custom buttons

### PR DESCRIPTION
**Pull request by sneazy-ibo**
>  opens up by longpressing status icon

The only thing left is fixing the system navbar bg, idk how aayush did it tho.

<details><summary>Preview</summary>
image
</details>

### CODE REVIEW

**Comment by rebelonion** [comment]
this seems like a great way for people to get scammed

**Comment by rebelonion** [comment]
probably to be on the safe side, yeah

**Comment by sneazy-ibo** [comment]
tbh I don't think that that many people will find out about this in order to abuse it since you have to login to discord first and find out that you can longpress the status switcher in order to set a custom button, additionally it would only be a pretest feature for the moment

**Comment by rebelonion** [comment]
>  I don't think that that many people will find out about this in order to abuse it 

this is a terrible mindset lol

**Comment by AbandonedCart** [comment]
Unless they have GitHub and can read...

**Comment by Sadwhy** [comment]
You should either use toggles or checkboxes because radio buttons shouldn't be used like that.

**Comment by sneazy-ibo** [comment]
> radio buttons shouldn't be used like that.

I used Radio buttons on purpose since it makes the most sense to use bc you cant toggle between multiple options in a choice option like here. Using checkboxes doesn't make sense because I would have to tick one option and untick the other option and for toggles I would have to add some logic that make only one toggle possible to be enabled. So radio buttons make the most sense here.

**Comment by Sadwhy** [comment]
So you can either display "stream on Dantotsu" or "view anilist" while the current rpc displays both?

**Comment by sneazy-ibo** [comment]
No the dirst button exists to redirect to the current media you are streaming. The second button is the one I made customizable.

**Comment by Sadwhy** [comment]
That's cool but is it possible to add option to turn the second button off?

**Comment by sneazy-ibo** [comment]
> That's cool but is it possible to add option to turn the second button off?

Oh that's a nice Idea, I will add that. Having two options makes the bottom sheet kinda weird looking bc of the height so I was looking for an Idea to add a third option again.

**Comment by AbandonedCart** [comment]
I think you meant to go the other direction with that last one. Looks like it deleted everything new.

**Comment by sneazy-ibo** [comment]
I used the strings file from the main branche 💀

**Comment by sneazy-ibo** [comment]
@AbandonedCart do you maybe know how I can get rid of this grey background behind the system navbar? I am trying to make it always use the color of the theme.

image

**Comment by AbandonedCart** [comment]
setNavigationTheme() from Functions will do it

**Comment by sneazy-ibo** [comment]
> setNavigationTheme() from Functions will do it

dumb question but how do I implement that function? I would have though of just thought of adding `bottomSheetDialog.window?.setNavigationTheme()` to the value

**Comment by AbandonedCart** [comment]
it extends an activity, so in an activity it would be `this.` or `this@NAME_OF_CLASS.` and in a fragment it would be `activity?.` or `requireActivity().`

**Comment by sneazy-ibo** [comment]
Did I still apply it wrong or is it just not compatible in my scenario?

image

**Comment by AbandonedCart** [comment]
It should already be applied to the settings activity by the initactivity, but then the dialog is showing its own overlay. Do you have the dialog set as fitsSystemWindows?

**Comment by sneazy-ibo** [comment]
<details><summary>Yes it's set to true</summary>
image

</details>

**Comment by AbandonedCart** [comment]
You may want to try false, but that adds a little fun with positioning

**Comment by sneazy-ibo** [comment]
Already tried that 😭

**Comment by AbandonedCart** [comment]
Same if you remove that line entirely?

**Comment by sneazy-ibo** [comment]
yes

**Comment by AbandonedCart** [comment]
Something seems off. It shouldn't act the same way for both.

**Comment by sneazy-ibo** [comment]
I don't know if that helps but it kinda looks like the grey area is on top of the bottom sheet like a frame layout.

<details><summary>Preview</summary>

https://github.com/rebelonion/Dantotsu/assets/41344259/d4a706a4-a662-41eb-845a-2c024fa6232a
</details>

**Comment by AbandonedCart** [comment]
You may need to set the window of the dialog to transparent

**Comment by AbandonedCart** [comment]
https://stackoverflow.com/a/64650272/461982

I remember needing to do that with alert dialog when I did a see-through background because they slap a frame on it.

**Comment by sneazy-ibo** [comment]
Thx amma try that out as soon as I wake up tmrw, it's already 5 am

**Review by rebelonion — APPROVED** [review]

**Pull request merged**
