### PR TITLE
Automatically search through sources

### PR DESCRIPTION
**Pull request by AbandonedCart**
Starting from the previously used source or 0, if this is a new item, this option will keep going down the list through sources until it finds a hit. It will stop at the end of the list. If you want to continue down the list after finding one, simply select the next source and it will continue down. It does not recycle back to the beginning to avoid an infinite loop.

### CODE REVIEW

**Comment by sneazy-ibo** [comment]
This is awesome tysm.

**Comment by AbandonedCart** [comment]
One thing it doesn't do is languages. It only checks whatever is set to the source's default or whatever was already chosen before.

**Review by rebelonion — APPROVED** [review]

**Comment by sneazy-ibo** [comment]
I see I see, I was wondering if it's possible to change the the work language selection works on extension settings. I've made a post on it some time ago after I gave up trying it myself. What are your thoughts about the following Idea?

<details>
  <summary>Language selector rework</summary>




</details>

**Comment by AbandonedCart** [comment]
That seems to make more sense he I understand it. You pick your languages first and then the extension only shows the ones you picked when it has them?

**Comment by sneazy-ibo** [comment]
Yes this is exactly what I mean! I had to struggle a lot explaining it to the discord members 😭

**Comment by AbandonedCart** [comment]
That would save a lot of time. One language in a list of 40 is not something I want to do twice.

**Pull request merged**
