### PR TITLE
Profile Stats Widget

### PR DESCRIPTION
**Pull request by AbandonedCart**
Who doesn't like a musical where you can sing along? For testing purposes.

#291

### CODE REVIEW

**Comment by AbandonedCart** [comment]
So the example was anime, days, manga, chapters. That doesn't really make sense. Shouldn't it be anime, episodes, manga, chapters?

**Comment by itsmechinmoy** [comment]
> So the example was anime, days, manga, chapters. That doesn't really make sense. Shouldn't it be anime, episodes, manga, chapters?

Anime days means total no of episodes watched (their time) in days

**Comment by aayush2622** [comment]
> So the example was anime, days, manga, chapters. That doesn't really make sense. Shouldn't it be anime, episodes, manga, chapters?

it was just  picked from a random site you can play around with it as you like

**Comment by AbandonedCart** [comment]
So that widget works now.

**Comment by rebelonion** [comment]
There's a test widget for currently airing in the code I haven't gotten around to finish yet. But the style is basically what I'm going for.

**Comment by rebelonion** [comment]
iirc setting the background color when you place the widget caused the widget service to never run. I'll probably look at it again.

**Comment by AbandonedCart** [comment]
I'll leave that one then.

**Comment by AbandonedCart** [comment]
I removed all the changes to that one, so the two won't collide.

**Comment by AbandonedCart** [comment]
Screenshot_20240325_214740

**Comment by AbandonedCart** [comment]
continue (whatever) is just an option for upcoming

**Comment by AbandonedCart** [comment]
It would almost make more sense to branch off into a separate widget and do a ViewFlipper

**Comment by AbandonedCart** [comment]
Well, this is going to be a fun undo

**Comment by AbandonedCart** [comment]
That's done enough. It's honestly just filling out options anyway. This isn't a featured widget.

**Pull request merged**
