### PR TITLE
feat: Added anime clear progress 

### PR DESCRIPTION
**Pull request by grayankit**

### CODE REVIEW

**Comment by itsmechinmoy** [comment]
Did u add a button for manga and anime?

**Comment by grayankit** [comment]
not yet where should I add it sad said it look bad on the previous one

**Comment by grayankit** [comment]
tell me and I will add it

**Comment by Dawn-used-yeet** [comment]
Add it in the hamburger menu.
Because it's not _that_ useful so many people won't use it.
But those who will, will see it.

**Comment by grayankit** [comment]
Screenshot_20241120_231836_Dantotsu

Screenshot_20241120_231920_Dantotsu

**Comment by itsmechinmoy** [comment]
Bwtter

**Pull request merged**
