### PR TITLE
Added Skip Recap Feature

### LINKED ISSUE #240: Skip recap
Auto skip recap function

### PR DESCRIPTION
**Pull request by JohnVictoryz**
This is to skip recap on like One Piece and other anime this is to close #240

### CODE REVIEW

**Comment by JohnVictoryz** [comment]
mb i left my temp config to the gradle.properties going to revert it now

**Comment by AbandonedCart** [comment]
Do you have 32GB RAM?

**Comment by JohnVictoryz** [comment]
> Do you have 32GB RAM? Asking because I recently found out that boosting the XmX / XmS anything over 1/4 of the RAM on hardware not strictly dedicated to building has the inverse effect of causing a bottleneck

Yes i actually have like 32GB RAM and it sort of caused and not caused a bottleneck i didn't see a big improvement in build times so i am not sure if i did something wrong or just it wont go faster

**Comment by AbandonedCart** [comment]
It seems silly, but you may want to try 4G and see if that speeds it up. Java gets weird when it has too much or too little.

**Comment by JohnVictoryz** [comment]
> It seems silly, but you may want to try 4G and see if that speeds it up. Java gets weird when it has too much or too little.

OK i will try it some other time

**Review by rebelonion — APPROVED** [review]

**Pull request merged**
