### PR TITLE
feat: add haptics to long click event

### PR DESCRIPTION
**Pull request by AbandonedCart**
Please, someone. Anyone. Tell me it's OK to let go....

### CODE REVIEW

**Comment by ARIF683** [comment]
@AbandonedCart Why dont you join discord?
A lot of people wants you there😅

**Comment by AbandonedCart** [comment]
I'm not really a fan of Discord.

**Comment by ARIF683** [comment]
Noooo 😢

**Comment by AbandonedCart** [comment]
It's nothing personal. It's the program that's the problem, not a specific server.

**Comment by ARIF683** [comment]
😂😅

**Comment by AbandonedCart** [comment]
Is there something specific someone was requesting?

**Comment by ARIF683** [comment]
Yeah, not one but many.

Some of them even change their username to 'add twisted umbrella to discord' 😂

**Comment by AbandonedCart** [comment]
Oh, the widget isn't actually connected. I didn't realize that. Alright, I'll wire the widget.

**Comment by ARIF683** [comment]
Really you gonna work on the widget 😍

**Comment by itsmechinmoy** [comment]
> Is there something specific someone was requesting?

Yh something like a rank progress bar in our profile and this 


Only in anime and manga not home

**Comment by ARIF683** [comment]
Here are the suggestion.

**Comment by AbandonedCart** [comment]
Stats is easy enough, currently airing is going to take a minute because that needs api garbage

**Comment by moonpic** [comment]
@AbandonedCart If you don't want to install discord, you can always use the browser **is a option** ¬

**Comment by aayush2622** [comment]
just join telegram if you have

**Comment by sneazy-ibo** [comment]
Awesome, I always wanted to know how to add those vibrations 😄

**Comment by AbandonedCart** [comment]
I owe it all to [Bob](https://stackoverflow.com/a/45605176/461982)

**Pull request merged**
