### PR TITLE
fix: swap chapter names and nav on RTL

### PR DESCRIPTION
**Pull request by AbandonedCart**
This was actually driving me nuts because I kept hitting the wrong button.

### CODE REVIEW

**Comment by AbandonedCart** [comment]
<details>
<summary>Left to right</summary>

Screenshot_20240309_140748
Screenshot_20240309_140803
</details>

<details>
<summary>Right to left</summary>

Screenshot_20240309_140637
Screenshot_20240309_140729
</details>

**Review by rebelonion — APPROVED** [review]

**Comment by AbandonedCart** [comment]
I didn't check up / down and down / up but that will be quick

**Comment by AbandonedCart** [comment]
Looks like everything is right with the chapters, but going down to up continues to progress the pages in top / bottom order (with the bottom going to the previous chapter). So a gesture starting at the top and swiping down **always** reduces the current page one, if that makes sense.

**Comment by rebelonion** [comment]
I can look

**Comment by AbandonedCart** [comment]
It's only in paged mode. In continuous, it swapped correctly.

**Pull request merged**
